version: '3'

services:

  nginx:
    image: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    # networks:  
    #   - test
    volumes:
      - type: bind
        source: /d/Dev/docker/nginx-www/nginx/html/
        target: /usr/share/nginx/html/
  
  # wordpress:
  #   image: wordpress
  #   build:
  #     context: ./wordpress/
  #     dockerfile: Dockerfile
  #   networks:
  #     - docker-network
  #   volumes:
  #   - type: volume
  #     source: wordpress
  #     target: /var/www/html
  #   depends_on: 
  #     nginx

  # DB:
  #   image: mariadb
  #   build:
  #     context: ./mariadb/
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     MARIADB_USER: achraf
  #     MARIADB_PASSWORD: my_cool_secre
  #     MARIADB_DATABASE: exmple-database
  #     MARIADB_ROOT_PASSWORD: my-secret-pw
  #   volumes:
  #     - type: bind
  #       source: shared_volume
  #       target: /var/lib/mysql
  #   networks:
  #     - inception-network
  #   depends_on:
  #     - nginx wordpress
