version: '3'

services:

  nginx:
    image: nginx
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    networks:  
      char
    volumes:
      - wordpress:/usr/share/nginx/html/
    ports:
      - "443:443"
  
  wordpress:
    image: wordpress
    build:
      context: ./wordpress/
      dockerfile: Dockerfile
    networks:
      char
    volumes:
    - wordpress:/var/www/html/
    # depends_on: 
    #   nginx

  # DB:
  #   image: mariadb
  #   build:
  #     context: ./mariadb/
  #     dockerfile: Dockerfile
  #   restart: always
  #   environment:
  #     MARIADB_USER: achraf
  #     MARIADB_PASSWORD: my_cool_secre
  #     MARIADB_DATABASE: exmple-database
  #     MARIADB_ROOT_PASSWORD: my-secret-pw
  #   volumes:
  #     - type: bind
  #       source: shared_volume
  #       target: /var/lib/mysql
  #   networks:
  #     - inception-network
  #   depends_on:
  #     - nginx wordpress
